package pl.bajerska.befindyourmeal.recipe;

public enum HealthLabel {

    ALCOHOL_FREE,
    CELERY_FREE,
    CRUSTACEAN_FREE,
    DAIRY_FREE,
    EGG_FREE,
    FISH_FREE,
    GLUTEN_FREE,
    KETO,
    KIDNEY_FRIENDLY,
    KOSHER,
    LOW_POTASSIUM,
    LUPINE_FREE,
    MUSTARD_FREE,
    NO_OIL_ADDED,
    NO_SUGAR,
    PALEO,
    PEANUT_FREE,
    PESCATARIAN,
    PORK_FREE,
    RED_MEAT_FREE,
    SESAME_FREE,
    SHELLFISH_FREE,
    SOY_FREE,
    SUGAR_CONSCIOUS,
    TREE_NUT_FREE,
    VEGAN,
    VEGETARIAN,
    WHEAT_FREE;
}

